TrialsForms/web/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrialsSurveys.Models;

namespace TrialsSurveys.Controllers
{
    public class PatientController : Controller
    {
        // GET: PatientList
        public ActionResult Index()
        {
            // Get a list of patients
            return View(Data.Patient.GetPatients());
        }

        // GET: PatientList/Details/5
        public ActionResult Details(string patientId)
        {
            
            return View(Data.Patient.GetPatient(patientId));
        }

        // GET: PatientList/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PatientList/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


    }
}

TrialsForms/web/Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrialsSurveys.Models;

namespace TrialsSurveys.Controllers
{
    public class SurveysController : Controller
    {
        // GET: Survey
        public ActionResult Index(string patientId = null)
        {
            var sms = new List<SurveysModel>();
            sms.Add(
            new SurveysModel
            {
                SurveyId = "AABB01",
                SurveyName = "The AA BB Survey",
                Completed = true
            });
            sms.Add(
            new SurveysModel
            {
                SurveyId = "CCDD02",
                SurveyName = "The CC DD Survey",
                Completed = false
            });
            ViewBag.PatientId = patientId;
            // When Index is called without parameters
            return View(sms);
        }

        // GET: Survey/Details/5
        public ActionResult Survey(string patientId, string surveyId)
        {
            SurveyBase survey;
            // Retrieve the model for the survey and display the correct survey
            switch (surveyId)
            {
                case "AABB01":
                    survey = new AQLQ_s_12
                    {
                        PatientId = patientId
                    };
                    break;
                case "CCDD02":
                    survey = new AQLQ_s_12
                    {
                        PatientId = patientId
                    };
                    break;
                default:
                    survey = new AQLQ_s_12
                    {
                        PatientId = patientId
                    };
                    break;
            }
            
            return View("AQLQ_s_12", survey);
        }

        // GET: Survey/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Survey/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Survey/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Survey/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Survey/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Survey/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TrialsForms/web/Views/Patient/Details.cshtml
@model TrialsSurveys.Models.PatientModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Details</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Details</strong>
            </li>
        </ol>
    </div>
</div>




<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Details PatientModel</h5>
                </div>
                <div class="ibox-content">


				    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClinicId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>


	    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary"})
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-white"})

                </div>
            </div>
        </div>
    </div>
 </div>

TrialsForms/web/Views/Patient/Index.cshtml
@model IEnumerable<TrialsSurveys.Models.PatientModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var clinic = ((List<TrialsSurveys.Models.PatientModel>) Model)[0].ClinicId;
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Clinic : @clinic</h2>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List of Patients</h5>
					<div class="ibox-tools">
						@Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-xs"})
					</div>
                </div>
                <div class="ibox-content">

<table id="patientTable" class="table table-striped">
    <tr>
        <th style="display: none;">
            @Html.DisplayNameFor(model => model.ClinicId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PatientId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr class="clickRow" id="@item.PatientId" data-url="@Url.Action("Index", "Surveys", new { patientId = item.PatientId })">
        <td style="display: none;">
            @Html.DisplayFor(modelItem => item.ClinicId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PatientId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
    </tr>
}

</table>

                </div>
            </div>
        </div>
    </div>
 </div>



<script>
    $(document).ready( function () {
        //$('#patientTable').DataTable();

        //alert("Started");
        $('.clickRow').click(function() {
            //alert("Handler for .click() called for:" + this.id);
            //http://localhost:59328/Surveys?patientId=DSA999
            var url = $(this).attr("data-url");
            //alert(url);
            window.location.href = url; 
        });
    } );
</script>