TrialsForms/web/Controllers/ClinicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrialsSurveys.Models;

namespace TrialsSurveys.Controllers
{
    public class ClinicController : Controller
    {
        // GET: PatientList
        public ActionResult Index()
        {
            // Get a list of patients
            return View(Data.Clinic.GetClinics());
        }

        // GET: PatientList/Details/5
        public ActionResult Details(string clinicId)
        {
            var cm = Data.Clinic.GetClinic(clinicId);
            return View(cm);
        }

        // GET: PatientList/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PatientList/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PatientList/Edit/5
        public ActionResult Edit(string clinicId)
        {
            var clinic = Data.Clinic.GetClinic(clinicId);
            return View(clinic);
        }

    }
}

TrialsForms/web/Views/Clinic/Create.cshtml
@model TrialsSurveys.Models.ClinicModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Create</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Create</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>



<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Create ClinicModel</h5>
                </div>
                <div class="ibox-content">

				@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicId)
                @Html.ValidationMessageFor(model => model.ClinicId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicName)
                @Html.ValidationMessageFor(model => model.ClinicName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated)
                @Html.ValidationMessageFor(model => model.DateCreated)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1)
                @Html.ValidationMessageFor(model => model.Address1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address2)
                @Html.ValidationMessageFor(model => model.Address2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Province, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Province)
                @Html.ValidationMessageFor(model => model.Province)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode)
                @Html.ValidationMessageFor(model => model.PostalCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FaxNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNumber)
                @Html.ValidationMessageFor(model => model.FaxNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress)
                @Html.ValidationMessageFor(model => model.EmailAddress)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
				@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-white"})
            </div>
        </div>
    </div>
}

                </div>
            </div>
        </div>
    </div>
 </div>

 

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrialsForms/web/Views/Clinic/Details.cshtml
@model TrialsSurveys.Models.ClinicModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Details</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Details</strong>
            </li>
        </ol>
    </div>
</div>




<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Details ClinicModel</h5>
                </div>
                <div class="ibox-content">


                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.ClinicId)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.ClinicId)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ClinicName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.ClinicName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.DateCreated)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.DateCreated)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Address1)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Address1)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Address2)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Address2)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.City)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.City)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Province)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Province)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PostalCode)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PostalCode)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PhoneNumber)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PhoneNumber)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.FaxNumber)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.FaxNumber)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.EmailAddress)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.EmailAddress)
                        </dd>

                    </dl>


                    @Html.ActionLink("Edit", "Edit", new { clinicId = Model.ClinicId }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-white" })

                </div>
            </div>
        </div>
    </div>
</div>

TrialsForms/web/Views/Clinic/Edit.cshtml
@model TrialsSurveys.Models.ClinicModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Edit</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Edit</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>




<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Edit ClinicModel</h5>
                </div>
                <div class="ibox-content">

				@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicId)
                @Html.ValidationMessageFor(model => model.ClinicId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicName)
                @Html.ValidationMessageFor(model => model.ClinicName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated)
                @Html.ValidationMessageFor(model => model.DateCreated)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1)
                @Html.ValidationMessageFor(model => model.Address1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address2)
                @Html.ValidationMessageFor(model => model.Address2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Province, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Province)
                @Html.ValidationMessageFor(model => model.Province)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode)
                @Html.ValidationMessageFor(model => model.PostalCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FaxNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNumber)
                @Html.ValidationMessageFor(model => model.FaxNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress)
                @Html.ValidationMessageFor(model => model.EmailAddress)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Details", new { clinicId = Model.ClinicId }, new { @class = "btn btn-white" })
            </div>
        </div>
    </div>
}


                </div>
            </div>
        </div>
    </div>
 </div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrialsForms/web/Views/Clinic/Index.cshtml
@model IEnumerable<TrialsSurveys.Models.ClinicModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Clinics</h2>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List of Clinics</h5>
                    <div class="ibox-tools">
                        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-xs" })
                    </div>
                </div>
                <div class="ibox-content">

                    <table class="table table-striped">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.ClinicId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ClinicName)
                            </th>
                            <th style="display: none;">
                                @Html.DisplayNameFor(model => model.DateCreated)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Address1)
                            </th>
                            <th style="display: none;">
                                @Html.DisplayNameFor(model => model.Address2)
                            </th>
                            <th style="display: none;">
                                @Html.DisplayNameFor(model => model.City)
                            </th>
                            <th style="display: none;">
                                @Html.DisplayNameFor(model => model.Province)
                            </th>
                            <th style="display: none;">
                                @Html.DisplayNameFor(model => model.PostalCode)
                            </th>
                            <th style="display: none;">
                                @Html.DisplayNameFor(model => model.PhoneNumber)
                            </th>
                            <th style="display: none;">
                                @Html.DisplayNameFor(model => model.FaxNumber)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.EmailAddress)
                            </th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr class="clickRow" id="@item.ClinicId" data-url="@Url.Action("Details", "Clinic", new { clinicId = item.ClinicId })">
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClinicId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClinicName)
                                </td>
                                <td style="display: none;">
                                    @Html.DisplayFor(modelItem => item.DateCreated)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Address1)
                                </td>
                                <td style="display: none;">
                                    @Html.DisplayFor(modelItem => item.Address2)
                                </td>
                                <td style="display: none;">
                                    @Html.DisplayFor(modelItem => item.City)
                                </td>
                                <td style="display: none;">
                                    @Html.DisplayFor(modelItem => item.Province)
                                </td>
                                <td style="display: none;">
                                    @Html.DisplayFor(modelItem => item.PostalCode)
                                </td>
                                <td style="display: none;">
                                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                                </td>
                                <td style="display: none;">
                                    @Html.DisplayFor(modelItem => item.FaxNumber)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EmailAddress)
                                </td>
                            </tr>
                        }

                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        //$('#patientTable').DataTable();

        $('.clickRow').click(function () {
            var url = $(this).attr("data-url");
            window.location.href = url;
        });
    });
</script>